#!/usr/bin/env bash
#
# sdlc-impl-plan-integrated.sh - 共有スクリプト統合の例
#
# このスクリプトは /sdlc-impl-plan コマンドに共有スクリプトを
# 統合する方法を示すサンプルです。
#
# 使用方法:
#   .claude/examples/sdlc-impl-plan-integrated.sh <FEATURE_ID>

set -euo pipefail

# スクリプトのディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# 共通関数を読み込み
source "${PROJECT_ROOT}/scripts/common-functions.sh"

#######################################
# メイン処理
#######################################
main() {
    # 引数チェック
    if [[ $# -ne 1 ]]; then
        log_error "Error: Invalid number of arguments"
        log_error "   Usage: $0 <FEATURE_ID>"
        exit 1
    fi

    local feature_id="$1"

    # プロジェクトルートに移動
    cd "$PROJECT_ROOT"

    log_info "Starting implementation plan generation for ${feature_id}"

    # ===== 共有スクリプト統合例 =====

    # 1. Feature 存在確認（共有関数使用）
    if ! check_feature_exists "$feature_id"; then
        log_error "   Action: /sdlc-init ${feature_id} を先に実行してください"
        exit 1
    fi

    log_success "Feature exists: ${feature_id}"

    # 2. Decision Status 確認（共有関数使用）
    local decision_status
    if ! decision_status=$(get_metadata_value "$feature_id" "DECISION_STATUS"); then
        log_error "   Action: .metadata に DECISION_STATUS を設定してください"
        exit 1
    fi

    if [[ "$decision_status" != "confirmed" ]]; then
        log_error "Error: Decision not confirmed"
        log_error "   Context: Current status: ${decision_status}"
        log_error "   Action: /sdlc-decision ${feature_id} で Decision を確定してください"
        exit 1
    fi

    log_success "Decision status: confirmed"

    # 3. ブランチ確認（共有スクリプト使用）
    if ! "${PROJECT_ROOT}/scripts/check-branch.sh" "$feature_id"; then
        exit 1
    fi

    # 4. ドキュメント読取
    log_info "Reading documents..."
    local feature_dir="sdlc/features/${feature_id}"

    if [[ ! -f "${feature_dir}/decisions.md" ]]; then
        log_error "Error: decisions.md not found"
        exit 1
    fi

    if [[ ! -f "${feature_dir}/00_context.md" ]]; then
        log_error "Error: context.md not found"
        exit 1
    fi

    log_success "All required documents found"

    # 5. Implementation Plan 生成（実際の実装では AI が生成）
    log_info "Generating implementation plan..."

    # ここで実際には AI が implementation plan を生成する
    # この例では既存のファイルをチェック
    if [[ -f "${feature_dir}/30_implementation_plan.md" ]]; then
        log_success "Implementation plan already exists"
    else
        log_warning "Implementation plan not found (would be generated by AI)"
    fi

    # 6. Metadata 更新（共有スクリプト使用）
    log_info "Updating metadata..."
    if ! "${PROJECT_ROOT}/scripts/update-metadata.sh" "$feature_id" "LAST_UPDATED" "$(date +%Y-%m-%d)"; then
        log_error "Failed to update metadata"
        exit 1
    fi

    # 完了メッセージ
    echo ""
    log_success "Implementation Plan 処理完了"
    echo ""
    echo "Feature: ${feature_id}"
    echo "Plan file: ${feature_dir}/30_implementation_plan.md"
    echo ""
    log_info "次のステップ: /sdlc-coding ${feature_id}"
}

# メイン処理実行
main "$@"
